### PR TITLE
Remove references to `oldRevision` and `newRevision` from the code

### LINKED ISSUE #1633: Remove references to `oldRevision` and `newRevision` from the code
This is part of a large refactor that is required for #1599.

Neither `oldRevision` nor `newRevision` are used anywhere in our code, so, for cleanup purposes, we should remove any references to them.

For QA:

There should be no observable changes in the app. Please check for regressions on the Compare page.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #1633

### CODE REVIEW

File: src/components/DiffView/index.tsx [hunk 1]
```diff
@@ -480,7 +481,7 @@ export class DiffViewBase extends React.Component<Props> {
         {extraMessages.length ? this.renderExtraMessages(extraMessages) : null}
 
         {diff && hunks && (
-          <React.Fragment key={`${diff.oldRevision}-${diff.newRevision}`}>
+          <React.Fragment key={version.id}>
```
Comment (willdurand) [inline src/components/DiffView/index.tsx:484]: Is this going to work when, on a compare page, we select a different base or head version? Does it update the page correctly?

Comment (bobsilverberg) [reply src/components/DiffView/index.tsx:484]: Hmm, let me check that...

Comment (bobsilverberg) [reply src/components/DiffView/index.tsx:484]: It seems to work fine on dev. Changing either pushes a new route, which reloads most of the page, so yes, it works. I don't think there's a use case for just updating the `DiffView` in place for a different set of versions. The `diff` changes, which means that the `FileTree` and the `CodeOverview` also change.
