### PR TITLE
Make reviewer tools link work for deleted add-ons

### LINKED ISSUE #1656: Link to reviewer tools is .../null for a deleted add-on
### Describe the problem and steps to reproduce it:

If the add-on is deleted, the link to the reviewer tools in the top left corner is: https://reviewers.addons.mozilla.org/reviewers/review/null

### What happened?

Link is https://reviewers.addons.mozilla.org/reviewers/review/null

### What did you expect to happen?

Link should be `https://reviewers.addons.mozilla.org/reviewers/review/<addon-id>`
(Note that we can't use slug here since deleted add-ons don't have a slug (that's why we link to .../null)

### PR DESCRIPTION
**Pull request by wagnerand**
Fix #1656.

### CODE REVIEW

File: src/reducers/versions.tsx [hunk 1]
```diff
@@ -195,7 +195,7 @@ type VersionAddon = {
   iconUrl: string;
   id: number;
   name: LocalizedStringMap;
-  slug: string;
+  slug: string | null;
```
Comment (willdurand) [inline src/reducers/versions.tsx:198]: It would be nice to update the addons-server docs too: https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-

Comment (wagnerand) [reply src/reducers/versions.tsx:198]: https://github.com/mozilla/addons-server/pull/14963

Comment (bobsilverberg) [reply src/reducers/versions.tsx:198]: I had a further thought about this. If we didn't want to allow `null` in `VersionAddon`, we could change `createInternalVersion` to that it stores an empty string in `slug` if it finds a `null` in the response. Doing that would eliminate the need for the ternary added to `src/components/Navbar/index.tsx` above. The downside is that we would no longer be able to tell the difference between a slug with a value of `''` and a slug with a value of `null`, so it might be better to just leave it like this.

@willdurand WDYT?

Comment (willdurand) [reply src/reducers/versions.tsx:198]: I'd prefer to have the `slug` declared as nullable like it's done here. @eviljeff confirmed that we have `null` slugs for deleted add-ons, which is something we definitely need to support in a tool designed for reviewers.

As you said, using an empty string would be confusing because this isn't allowed.

Comment (bobsilverberg) [reply src/reducers/versions.tsx:198]: Thanks @willdurand. In case it isn't entirely clear, @wagnerand, this means just leave it as it is now.
