### PR TITLE
Fix empty folder node height

### LINKED ISSUE #258: Empty node height is wrong according to Storybook
The height of an "empty folder" node is not the same as the other nodes, see:

screen shot 2019-02-22 at 14 47 34

It should be:

screen shot 2019-02-22 at 14 47 25

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #258 

---

This is a small fix for a small issue I noticed in Storybook 😎 

Before:

screen shot 2019-02-22 at 14 47 34

After:

screen shot 2019-02-22 at 14 47 25

### CODE REVIEW

File: src/components/FileTreeNode/index.tsx [hunk 1]
```diff
@@ -58,7 +58,7 @@ class FileTreeNodeBase<TreeNodeType> extends React.Component<PublicProps> {
             renderChildNodes()
           ) : (
             <ListGroup.Item
-              className={styles.emptyNodeDirectory}
+              className={makeClassName(styles.node, styles.emptyNodeDirectory)}
```
Comment (kumar303) [inline src/components/FileTreeNode/index.tsx]: Where does `emptyNodeDirectory` come from? I can't find it.

Comment (willdurand) [reply src/components/FileTreeNode/index.tsx]: It's just a CSS class, mostly used in unit tests so far. It's possible to declare CSS class names without any CSS in `styles.module.scss`. I used to write an empty definition (`.cls {}`) but a review comment asked me to get rid of that if there was no definition, so 🤷‍♂️

Comment (kumar303) [reply src/components/FileTreeNode/index.tsx]: > It's possible to declare CSS class names without any CSS in `styles.module.scss`.

Huh, I guess that's why TypeScript didn't catch the typo'd class name in that other patch.
