### PR TITLE
Fix `start-local-*` commands

### LINKED ISSUE #899: yarn start-local-prod is broken (blank page, CSP errors)
### Describe the problem and steps to reproduce it:

- Run `yarn start-local-prod` [as documented](https://github.com/mozilla/addons-code-manager#yarn-start-local-prod)
- Clear your browser cache
- Load http://localhost:3000

### What happened?

The page at `localhost:3000` is blank and there are numerous console errors:

Screenshot 2019-07-02 09 42 04

### What did you expect to happen?

The page should load

### Anything else we should know?

Maybe the CDN URL just needs fixing or maybe there are CSP problems, too.

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #899

### CODE REVIEW

File: src/pages/Index/index.tsx [hunk 1]
```diff
@@ -22,7 +22,9 @@ export class IndexBase extends React.Component<Props> {
     _log: log,
     allowErrorSimulation:
       process.env.REACT_APP_UNSAFE_ERROR_SIMULATION === 'true',
-    showLocalDevLinks: process.env.REACT_APP_IS_LOCAL_DEV === 'true',
+    showLocalDevLinks:
+      process.env.NODE_ENV === 'development' &&
```
Comment (willdurand) [inline src/pages/Index/index.tsx]: This prevents the links to be shown when a production build is served locally.
