### PR TITLE
Dispatch begin/abort actions when fetching a version and avoid infinite fetch/error loop

### LINKED ISSUE #556: `fetchFile` should dispatch `beginFetchVersionFile` before loading version info/file
While working on [a different patch for the `Browse` component](https://github.com/mozilla/addons-code-manager/issues/551#issuecomment-481714926), I discovered an inconsistency between `fetchVersion` and `fetchVersionFile`: `fetchVersion` does not set the `loading` boolean to `true` before loading the file.

This might be a problem given that the `Browse` component tries to fetch a file (by calling `fetchVersionFile`) when the loading state is `false`. We should probably dispatch `beginFetchVersionFile` before loading the info/file.

### LINKED ISSUE #602: Infinite loop for 404 errors generated by an invalid addon/version id in the browse view
**STR:**

Open the browse view for an add-on and make sure that either the addon or the version Id is incorrect:
see https://code.addons-dev.allizom.org/en-US/browse/616653/versions/1655549/

**Actual result:**
An infinite loop for the 404 error 

**Expected result:**
The 404 error and its corresponding message should be caught only once

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #602
Fixes #556 

---

This patch is similar to the one merged to solve https://github.com/mozilla/addons-code-manager/issues/565. I added a bunch of early returns in the `reducer` (with `log.error` calls and test cases).

### CODE REVIEW

File: src/reducers/versions.tsx [hunk 1]
```diff
@@ -735,6 +764,12 @@ const reducer: Reducer<VersionsState, ActionType<typeof actions>> = (
       const { selectedPath, versionId } = action.payload;
 
       const version = state.versionInfo[versionId];
+
+      if (!version) {
+        _log.error(`Version missing for versionId: ${versionId}`);
```
Comment (bobsilverberg) [inline src/reducers/versions.tsx]: I wonder if this should throw an actual error, rather than just logging. It shouldn't really be possible to have called `updateSelectedPath` without having a corresponding version loaded.

File: src/reducers/versions.tsx [hunk 2]
```diff
@@ -757,12 +792,19 @@ const reducer: Reducer<VersionsState, ActionType<typeof actions>> = (
     case getType(actions.toggleExpandedPath): {
       const { path, versionId } = action.payload;
 
-      const { expandedPaths } = state.versionInfo[versionId];
+      const version = state.versionInfo[versionId];
+
+      if (!version) {
+        _log.error(`Version missing for versionId: ${versionId}`);
```
Comment (bobsilverberg) [inline src/reducers/versions.tsx]: I wonder if this should throw an actual error, rather than just logging. It shouldn't really be possible to have called `toggleExpandedPath` without having a corresponding version loaded.

File: src/reducers/versions.tsx [hunk 3]
```diff
@@ -776,8 +818,13 @@ const reducer: Reducer<VersionsState, ActionType<typeof actions>> = (
       const { versionId } = action.payload;
 
       const version = state.versionInfo[versionId];
-      const { entries } = version;
-      const expandedPaths = entries
+
+      if (!version) {
+        _log.error(`Version missing for versionId: ${versionId}`);
```
Comment (bobsilverberg) [inline src/reducers/versions.tsx]: I wonder if this should throw an actual error, rather than just logging. It shouldn't really be possible to have called `expandedTree` without having a corresponding version loaded.

File: src/reducers/versions.tsx [hunk 4]
```diff
@@ -796,12 +843,19 @@ const reducer: Reducer<VersionsState, ActionType<typeof actions>> = (
     case getType(actions.collapseTree): {
       const { versionId } = action.payload;
 
+      const version = state.versionInfo[versionId];
+
+      if (!version) {
+        _log.error(`Version missing for versionId: ${versionId}`);
```
Comment (bobsilverberg) [inline src/reducers/versions.tsx]: I wonder if this should throw an actual error, rather than just logging. It shouldn't really be possible to have called `collapseTree` without having a corresponding version loaded.

File: src/reducers/versions.spec.tsx [hunk 5]
```diff
@@ -121,6 +121,20 @@ describe(__filename, () => {
       );
     });
 
+    it('logs an error when updateSelectedPath is called for an unknown version', () => {
```
Comment (bobsilverberg) [inline src/reducers/versions.spec.tsx]: The four test cases added that check that an error was logged for different actions are all essentially identical, other than the action being called, so I wonder if either a helper, or an `it.each()` would be appropriate for these to reduce the duplication in this file?

File: src/reducers/versions.spec.tsx [hunk 6]
```diff
@@ -1618,4 +1719,94 @@ describe(__filename, () => {
...
+      const version = fakeVersion;
+      let state = reducer(undefined, actions.loadVersionInfo({ version }));
+
+      const abortFetchVersionId = version.id + 123;
+      state = reducer(
+        state,
+        actions.abortFetchVersion({ versionId: abortFetchVersionId }),
+      );
+
+      expect(state.versionInfo[version.id]).toEqual(expect.any(Object));
```
Comment (bobsilverberg) [inline src/reducers/versions.spec.tsx]: Why are you using `any(Object)` here rather than `createInternalVersion(version)`? You are checking that the other version wasn't set to `null` but not necessarily that it was untouched in any way.

**Comment by willdurand** [comment]
> This looks good, thanks @willdurand. I have some questions about the tests, and also about whether we should be throwing errors instead of logging.

@bobsilverberg for a similar case, we used `log.error` instead of throwing: https://github.com/mozilla/addons-code-manager/blob/aadb04c6983341e10d56ab754403dd18093fd803/src/reducers/versions.tsx#L838, so 🤷‍♂️

File: src/reducers/versions.spec.tsx [hunk 7]
```diff
@@ -1618,4 +1719,94 @@ describe(__filename, () => {
...
+      const version = fakeVersion;
+      let state = reducer(undefined, actions.loadVersionInfo({ version }));
+
+      const beginFetchVersionId = version.id + 123;
+      state = reducer(
+        state,
+        actions.beginFetchVersion({ versionId: beginFetchVersionId }),
+      );
+
+      expect(state.versionInfo[version.id]).toEqual(expect.any(Object));
```
[the remark this answers is not in the document]
Comment (willdurand) [reply src/reducers/versions.spec.tsx]: The purpose of the test case isn't to assert this value, only making sure it's not `null` or `undefined`. That's why `expect.any(Object)` is used here. The exact shape of this object is covered by another test case.

**Comment by bobsilverberg** [comment]
> @bobsilverberg for a similar case, we used `log.error` instead of throwing: https://github.com/mozilla/addons-code-manager/blob/aadb04c6983341e10d56ab754403dd18093fd803/src/reducers/versions.tsx#L838
> 
> so.. 🤷‍♂️ 

I would argue that maybe that other function should be changed too. It seems reasonable to throw an error when we encounter a case that we don't believe should ever have happened.

**Comment by willdurand** [comment]
> I would argue that maybe that other function should be changed too. It seems reasonable to throw an error when we encounter a case that we don't believe should ever have happened.

I don't know. `log.error` will send the error to sentry, without breaking the site for the end user and, for developers, logged errors are in red in the console.

I don't have a strong opinion on that but that would break the contract of a reducer: https://redux.js.org/glossary#reducer (pureness and side-effect free).

File: src/reducers/versions.tsx (hunk 1 above)
Comment (kumar303) [inline src/reducers/versions.tsx]: > I wonder if this should throw an actual error

I guess either way works but it would be a bit better to throw an error so that Sentry gets a stack trace. It might render an error boundary and make the app unusable but at least that would be less confusing than the user seeing no change at all from their action. Thrown errors are easier to test, too 😅

File: src/reducers/versions.tsx [hunk 8]
```diff
@@ -356,10 +365,7 @@ export const getVersionFiles = (versions: VersionsState, versionId: number) => {
   return versions.versionFiles[versionId];
 };
 
-export const getVersionInfo = (
-  versions: VersionsState,
-  versionId: number,
-): Version | void => {
```
[the remark this answers is not in the document]
Comment (kumar303) [reply src/reducers/versions.tsx]: Well, I should ask, is TypeScript still inferring the wrong type?

[the remark this answers is not in the document]
Comment (willdurand) [reply src/reducers/versions.tsx]: If I remove `as Version` in a test file (on a `getVersionInfo` call), I get this TS error:

```
Type 'Version | null | undefined' is not assignable to type 'Version'. Type 'undefined' is not assignable to type 'Version'.
```

So I guess it has been fixed either _via_ a TS upgrade or _via_ the type change in this patch.

**Comment by willdurand** [comment]
@bobsilverberg I updated this patch to throw errors all the time as both @kumar303 and you think it's better (I am fine with that, I removed all the log calls to be consistent).

**Comment by willdurand** [comment]
> I think this infinite loop is new behavior because I've definitely triggered 404s in the past.

Yep, I agree. There is a link to an error page in the `Index` component. We would have noticed the infinite loop before.

File: src/reducers/versions.tsx (hunk 8 above)
[the remark this answers is not in the document]
Comment (kumar303) [reply src/reducers/versions.tsx]: ok, good

File: src/reducers/versions.spec.tsx [hunk 9]
```diff
@@ -121,6 +121,15 @@ describe(__filename, () => {
       );
     });
 
+    it('throws an error when updateSelectedPath is called for an unknown version', () => {
+      expect(() => {
+        reducer(
+          undefined,
+          actions.updateSelectedPath({ selectedPath: 'pa/th', versionId: 123 }),
+        );
+      }).toThrow();
```
Comment (bobsilverberg) [inline src/reducers/versions.spec.tsx]: In a lot of our tests we assert on the actual error message. Maybe that's overkill (and introduces a maintenance burden if the messages change), but I wanted to raise it here as an inconsistency. This same comment applies to all the `expect(...).toThrow()` tests.

Comment (kumar303) [reply src/reducers/versions.spec.tsx]: Yeah, since so many errors *could* be thrown, I think it's always helpful to assert some part of the message.
