### PR TITLE
Don't trim diffs by default

### LINKED ISSUE #1230: Disable trimming of large (slow) diffs
### Describe the problem and steps to reproduce it:

* Load a large diff (see https://github.com/mozilla/addons-code-manager/issues/971) in compare mode

### What happened?

The diff should not be truncated

### What did you expect to happen?

The diff is currently truncated as an attempt to speed up the page

### Anything else we should know?

We'd like to show the entire diff as a workaround to https://github.com/mozilla/addons-code-manager/issues/971 which is about broken navigation due to the trimmed file.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #1230

### CODE REVIEW

File: src/components/SlowPageAlert/index.tsx [hunk 1]
```diff
@@ -11,19 +11,24 @@ import {
 type GetTextForSlowState = (allowSlowPages: boolean) => string;
 
 export type PublicProps = {
-  _shouldAllowSlowPages?: (location: Location) => boolean;
+  _shouldAllowSlowPages?: typeof shouldAllowSlowPages;
+  defaultAllowSlowPagesToTrue?: boolean;
```
Comment (kumar303) [inline src/components/SlowPageAlert/index.tsx]: How about `allowSlowPagesByDefault`?

File: src/utils.tsx [hunk 2]
```diff
@@ -120,6 +120,17 @@ export const makeReviewersURL = ({
   return path;
 };
 
-export const shouldAllowSlowPages = (location: Location) => {
-  return queryString.parse(location.search)[allowSlowPagesParam] === 'true';
+export const shouldAllowSlowPages = ({
+  defaultToTrue = false,
```
Comment (kumar303) [inline src/utils.tsx]: how about `allowByDefault`?

**Comment by bobsilverberg** [comment]
Good suggestions, thanks @kumar303.
