### PR TITLE
Change the signature of `getVersionInfo()`

### LINKED ISSUE #442: Fix return type of getVersionInfo
The `getVersionInfo` selector currently looks like this:

https://github.com/mozilla/addons-code-manager/blob/5efef278ed8e2e3b7b2d7dfa1ceae7451cf3d801/src/reducers/versions.tsx#L309-L311

The return type should be `Version | void` because the `versionId` might be missing from `versions.versionInfo`. However, TypeScript infers the return type only as `Version`.

Let's declare the correct return type and fix the fallout (there is a lot). It should look more like:

```tsx
export const getVersionInfo = (
  versions: VersionsState,
  versionId: number,
): Version | void => {
  return versions.versionInfo[versionId];
};
```

This change will help ensure that all components are working with mapped Redux props correctly.

### LINKED ISSUE #534: An error occurs when trying to change the "new" version in the Compare page
### Describe the problem and steps to reproduce it:

1. Go to https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541794...1541798/
2. Select a "new" version, e.g., `1.4.0`

### What happened?

It crashes.

### What did you expect to happen?

It does not crash.

### Anything else we should know?

Error in local dev is:

```
TypeError: version is undefined
render
src/components/DiffView/index.tsx:205

  202 | 
  203 | return (
  204 |   <LinterProvider
> 205 |     versionId={version.id}
      | ^  206 |     validationURL={version.validationURL}
  207 |     selectedPath={version.selectedPath}
  208 |   >
```

Selecting another "old" version seems to work.

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #534 
Fixes #442

---

### CODE REVIEW

File: src/reducers/versions.tsx [hunk 1]
```diff
@@ -756,7 +759,13 @@ const reducer: Reducer<VersionsState, ActionType<typeof actions>> = (
     case getType(actions.loadDiff): {
       const { baseVersionId, headVersionId, version } = action.payload;
 
-      const { entries, selectedPath } = getVersionInfo(state, headVersionId);
+      const headVersion = getVersionInfo(state, headVersionId);
+      if (!headVersion) {
+        _log.debug(`Version missing for headVersionId: ${headVersionId}`);
```
Comment (bobsilverberg) [inline src/reducers/versions.tsx]: Should this be `log.warn` because this seems like a pretty critical situation? Just returning `state` makes sense, but it will appear as if nothing happened. I suppose `debug` will also put a message in the console, but `warn` seems more appropriate.

File: src/reducers/versions.spec.tsx [hunk 2]
```diff
@@ -352,6 +352,39 @@ describe(__filename, () => {
...
+      const baseVersionId = 2;
+      const path = 'some/other/file.js';
+      const _log = createFakeLogger();
+
+      const version = {
+        ...fakeVersionWithDiff,
+        file: {
+          ...fakeVersionWithDiff.file,
+          // eslint-disable-next-line @typescript-eslint/camelcase
+          selected_file: path,
```
Comment (bobsilverberg) [inline src/reducers/versions.spec.tsx]: Why do you need to override `selected_file` with anything? It doesn't seem to have any impact on what you are testing here. It only cares about whether the version being requested is present or not.

File: src/reducers/versions.spec.tsx [hunk 3]
```diff
@@ -352,6 +352,39 @@ describe(__filename, () => {
...
+
+      const versionsState = reducer(
+        undefined,
+        actions.loadDiff({
+          addonId,
+          baseVersionId,
+          headVersionId,
+          version,
+        }),
+        // TS looks confused about the third optional argument.
```
Comment (bobsilverberg) [inline src/reducers/versions.spec.tsx]: This is odd. Can we do something better with the definition to make TS less confused?

File: src/pages/Compare/index.spec.tsx [hunk 4]
```diff
@@ -128,6 +128,23 @@ describe(__filename, () => {
...
 
+  it('renders a loading message when no diff has been loaded', () => {
+    const addonId = 123;
+    const baseVersionId = 1;
+    const version = { ...fakeVersionWithDiff, id: baseVersionId + 1 };
+    const store = configureStore();
+    store.dispatch(versionsActions.loadVersionInfo({ version }));
+
+    const root = render({
+      addonId: String(addonId),
```
Comment (bobsilverberg) [inline src/pages/Compare/index.spec.tsx]: I'm not sure why you're overriding `addonId` - it doesn't seem to have any impact on the test. Note that this is reflected in by diff above.

File: src/pages/Compare/index.spec.tsx [hunk 5]
```diff
@@ -128,6 +128,23 @@ describe(__filename, () => {
     expect(root.find(VersionChooser)).toHaveProp('addonId', addonId);
   });
 
+  it('renders a loading message when no diff has been loaded', () => {
+    const addonId = 123;
+    const baseVersionId = 1;
```
Comment (bobsilverberg) [inline src/pages/Compare/index.spec.tsx]: I'm not sure why you're specifying a `baseVersionId` here. The only place you use it is to set the `id` when creating `version`, and then later you just use `version.id`, so it seems like you might as well just remove `baseVersionId`, and not bother overriding `id` for the version.

I.e., this looks like the same test:

```diff
diff --git a/src/pages/Compare/index.spec.tsx b/src/pages/Compare/index.spec.tsx
index b3111d9..b7cfddd 100644
--- a/src/pages/Compare/index.spec.tsx
+++ b/src/pages/Compare/index.spec.tsx
@@ -129,14 +129,11 @@ describe(__filename, () => {
   });
 
   it('renders a loading message when no diff has been loaded', () => {
-    const addonId = 123;
-    const baseVersionId = 1;
-    const version = { ...fakeVersionWithDiff, id: baseVersionId + 1 };
+    const version = fakeVersionWithDiff;
     const store = configureStore();
     store.dispatch(versionsActions.loadVersionInfo({ version }));
 
     const root = render({
-      addonId: String(addonId),
       headVersionId: String(version.id),
       store,
     });
```

File: src/pages/Browse/index.tsx [hunk 6]
```diff
@@ -40,7 +40,7 @@ type PropsFromState = {
   apiState: ApiState;
   file: VersionFile | null | void;
   fileIsLoading: boolean;
-  version: Version;
+  version: Version | void;
```
Comment (bobsilverberg) [inline src/pages/Browse/index.tsx]: I'm surprised that this can just be changed without any fallout in this component, but I guess it can!

File: src/reducers/versions.tsx (hunk 1 above)
Comment (willdurand) [reply src/reducers/versions.tsx]: I don't really when this is supposed to occur to be honest.

File: src/reducers/versions.spec.tsx (hunk 2 above)
Comment (willdurand) [reply src/reducers/versions.spec.tsx]: It does not matter indeed.

File: src/reducers/versions.spec.tsx (hunk 3 above)
Comment (willdurand) [reply src/reducers/versions.spec.tsx]: No, we can't. This is existing code.

Comment (willdurand) [reply src/reducers/versions.spec.tsx]: This is because TS does not expect a third argument to `reducer` but there is no reason: an optional argument can be added to a function without any problem in JS.

File: src/reducers/versions.spec.tsx [hunk 7]
```diff
@@ -352,6 +352,30 @@ describe(__filename, () => {
...
+        // @ts-ignore
+        { _log },
```
Comment (kumar303) [inline src/reducers/versions.spec.tsx]: It makes sense that TS won't allow this because Redux has a specific reducer signature and this doesn't match it. We can make a pretty good guess that the reducer will still work in the wild with a `_log` option *but* I think it would be fine to honor the type signature and just change the design. We could do it like this:

```tsx
const createReducer = ({ _log = log } = {}) => {
  const reducer: Reducer<VersionsState, ActionType<typeof actions>> = (
    state = initialState,
    action,
  ): VersionsState => {
    switch (action.type) {
      // ...
    }
  };

  return reducer;
};

const reducer = createReducer();
export default reducer;
```

This might be super annoying -- just throwing it out as an idea (not a change request).

File: src/reducers/versions.tsx [hunk 8]
```diff
@@ -756,7 +759,13 @@ const reducer: Reducer<VersionsState, ActionType<typeof actions>> = (
     case getType(actions.loadDiff): {
       const { baseVersionId, headVersionId, version } = action.payload;
 
-      const { entries, selectedPath } = getVersionInfo(state, headVersionId);
+      const headVersion = getVersionInfo(state, headVersionId);
+      if (!headVersion) {
+        _log.error(`Version missing for headVersionId: ${headVersionId}`);
```
Comment (kumar303) [inline src/reducers/versions.tsx]: I'll be honest. I don't think it's important to use dependency injection to test a log message 😄 If you add a test that runs this line of code to make sure no errors are thrown, that's enough. TypeScript will catch all other mistakes that could go wrong with this log message. It was way more important to fully test function calls like this before static analysis.

Comment (willdurand) [reply src/reducers/versions.tsx]: Yep, this is more to reach 100% code coverage than anything else now.
